[project]
name = "odoo-addons-open-synergy-ssi-dashboard"
version = "19.0.20260719.8"
dependencies = [
    "odoo-addon-ssi_dashboard==19.0.*",
    "odoo-addon-ssi_dashboard_color_scheme_ssi==19.0.*",
    "odoo-addon-ssi_dashboard_item_chart==19.0.*",
    "odoo-addon-ssi_dashboard_item_kpi==19.0.*",
    "odoo-addon-ssi_dashboard_item_list==19.0.*",
    "odoo-addon-ssi_dashboard_item_tile==19.0.*",
    "odoo-addon-ssi_dashboard_item_todo==19.0.*",
    "odoo-addon-ssi_dashboard_source_api==19.0.*",
    "odoo-addon-ssi_dashboard_source_query==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
